/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaEmail.java
 *
 * Created on 19/05/2016, 13:00:18
 */
package view;

import java.io.File;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.Color;
import javax.swing.border.LineBorder;

import com.myscrum.controller.Controle;
import com.myscrum.model.Sessao;

import java.awt.SystemColor;
import java.awt.Toolkit;

import javax.swing.SwingConstants;
import javax.swing.JTextField;
import java.awt.Font;
import java.awt.Image;

import javax.swing.JLabel;


public class ContatoTela extends javax.swing.JFrame {

	/**
	 * Desenvolvido por Abner Matias e Pedro Henrique
	 * 
	 */
	private static final long serialVersionUID = 1L;


	Sessao s = new Sessao();
 

File[] Anexo;

    /** Creates new form JanelaEmail */
    public ContatoTela() {
    	
    	super("Contato");
    	setResizable(false);//maximazaÁ„o do frame desativada
    	
    	//mudando Icone do Frame
        java.net.URL url = this.getClass().getResource("/com/myscrum/assets/setIcon1.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    	
    	addWindowListener(new WindowAdapter() {
    		@Override
    		public void windowClosing(WindowEvent e) {
    
    			Controle.setContato(false);
    			dispose();
    		}
    	});
        initComponents();
        EnderecoAnexo.setEditable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    
        jPanel3 = new javax.swing.JPanel();
        Destinatario = new javax.swing.JTextField();
        Destinatario.setEditable(false);
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel7 = new javax.swing.JLabel();
        Assunto = new javax.swing.JTextField();
        EnderecoAnexo = new javax.swing.JTextField();
        BotaoEnviar =   new javax.swing.JButton();
        BotaoEnviar.setBackground(new Color(163, 184, 204));
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setBorder(new LineBorder(Color.LIGHT_GRAY));
        jLabel1 = new javax.swing.JLabel();
        ServidorSMTP = new javax.swing.JTextField();
        ServidorSMTP.setForeground(SystemColor.text);
        ServidorSMTP.setBackground(SystemColor.textHighlight);
        ServidorSMTP.setEditable(false);
        jLabel2 = new javax.swing.JLabel();
        Porta = new javax.swing.JTextField();
        Porta.setHorizontalAlignment(SwingConstants.CENTER);
        Porta.setForeground(SystemColor.text);
        Porta.setBackground(SystemColor.textHighlight);
        Porta.setEditable(false);
        BotaoExcluir = new javax.swing.JButton();
        BotaoAnexo = new javax.swing.JButton();
       
        jPanel3.setBackground(Color.WHITE);
        jPanel3.setPreferredSize(new java.awt.Dimension(786, 543));

        Destinatario.setFont(new java.awt.Font("Tahoma", 0, 18));
        Destinatario.setText("supmyscrum@gmail.com");
        Destinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinatarioActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel7.setText("Assunto* :");

        Assunto.setFont(new java.awt.Font("Tahoma", 0, 18));
        Assunto.setText("");

        EnderecoAnexo.setFont(new java.awt.Font("Tahoma", 0, 14));

        BotaoEnviar.setFont(new java.awt.Font("Tahoma", 1, 14));
    
        BotaoEnviar.setText("Enviar");
        BotaoEnviar.addActionListener(new java.awt.event.ActionListener() {
           
			public void actionPerformed(java.awt.event.ActionEvent evt) {                
           		if(Assunto.getText().equals("")) {
           			
           			JOptionPane.showMessageDialog(null, "Pressencha o campo ObrigatÛrio ");
           			Assunto.setFocusable(true);
           		}else {
				
				BotaoEnviarActionPerformed(evt);    	
           		}
            }
        });

        jPanel2.setBackground(Color.WHITE);
        jPanel2.setPreferredSize(new java.awt.Dimension(688, 66));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Servidor SMTP:");

        ServidorSMTP.setFont(new java.awt.Font("Tahoma", 0, 18));
        ServidorSMTP.setText("email-ssl.com.br");
        

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setText("Porta");

        Porta.setFont(new java.awt.Font("Tahoma", 0, 18));
        Porta.setText("465");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(ServidorSMTP, GroupLayout.PREFERRED_SIZE, 252, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(Porta, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        			.addGap(96))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(Porta, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2)
        				.addComponent(ServidorSMTP, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel1))
        			.addContainerGap())
        );
        jPanel2.setLayout(jPanel2Layout);

        BotaoExcluir.setText("Excluir");
        BotaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirActionPerformed(evt);
            }
        });

        BotaoAnexo.setFont(new java.awt.Font("Tahoma", 0, 12));
        BotaoAnexo.setText("Anexo");
        BotaoAnexo.setToolTipText("");
        BotaoAnexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAnexoActionPerformed(evt);
               
            }
        });
        
        NomeRemetente = new JTextField();
        NomeRemetente.setText(s.getNome()); ///setando o nome
        NomeRemetente.setFont(new Font("Tahoma", Font.PLAIN, 18));
        
        label = new JLabel();
        label.setText("Nome:");
        label.setFont(new Font("Tahoma", Font.PLAIN, 18));
        jLabel6 = new javax.swing.JLabel();
        
                jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18));
                jLabel6.setText("Para:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel3Layout.createSequentialGroup()
        							.addGap(81)
        							.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 643, GroupLayout.PREFERRED_SIZE))
        						.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 733, GroupLayout.PREFERRED_SIZE))
        					.addGap(1443))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(BotaoEnviar)
        					.addContainerGap(2125, Short.MAX_VALUE))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING, false)
        						.addGroup(jPanel3Layout.createSequentialGroup()
        							.addComponent(BotaoAnexo)
        							.addGap(18)
        							.addComponent(EnderecoAnexo))
        						.addGroup(Alignment.LEADING, jPanel3Layout.createSequentialGroup()
        							.addComponent(jLabel7)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(Assunto, GroupLayout.PREFERRED_SIZE, 564, GroupLayout.PREFERRED_SIZE)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(BotaoExcluir, GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        					.addGap(1452))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(label, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(NomeRemetente, GroupLayout.PREFERRED_SIZE, 226, GroupLayout.PREFERRED_SIZE)
        					.addGap(51)
        					.addComponent(jLabel6)
        					.addGap(18)
        					.addComponent(Destinatario, GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        					.addGap(1462))))
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        			.addGap(31)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(NomeRemetente, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        				.addComponent(label, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
        				.addComponent(Destinatario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel6))
        			.addGap(32)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel7)
        				.addComponent(Assunto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(34)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(BotaoAnexo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(BotaoExcluir)
        				.addComponent(EnderecoAnexo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(47)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE)
        				.addComponent(BotaoEnviar, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
        			.addGap(118))
        );
        Mensagem = new javax.swing.JTextArea();
        jScrollPane1.setViewportView(Mensagem);
        
                Mensagem.setColumns(20);
                Mensagem.setFont(new java.awt.Font("Tahoma", 0, 18));
                Mensagem.setLineWrap(true);
                Mensagem.setRows(5);
                Mensagem.setText("Digite sua Mensagem aqui.");
                Mensagem.setWrapStyleWord(true);
        jPanel3.setLayout(jPanel3Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 768, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        			.addGap(124))
        );
        getContentPane().setLayout(layout);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-804)/2, (screenSize.height-614)/2, 776, 489);
    }// </editor-fold>//GEN-END:initComponents

private void DestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinatarioActionPerformed

}//GEN-LAST:event_DestinatarioActionPerformed

private void BotaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEnviarActionPerformed
    EmailAnexo();

}//GEN-LAST:event_BotaoEnviarActionPerformed

private void BotaoAnexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAnexoActionPerformed

    JFileChooser file = new JFileChooser();
    file.setMultiSelectionEnabled(true);
    file.setFileSelectionMode(JFileChooser.FILES_ONLY);
    int i = file.showOpenDialog(null);
    if (i == 1) {
        EnderecoAnexo.setText("");
        Anexo = null;
    } else {
        Anexo = file.getSelectedFiles();
        
        String SomaAnexo1 = "";
        String SomaAnexo2 = "";
        for (File enderec : Anexo) {
            EnderecoAnexo.setText(enderec.getPath());
            SomaAnexo1 = EnderecoAnexo.getText();
            SomaAnexo2 = SomaAnexo2 + SomaAnexo1 + ";";
            EnderecoAnexo.setText(SomaAnexo2);

        }
    }


}//GEN-LAST:event_BotaoAnexoActionPerformed

private void BotaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirActionPerformed
    EnderecoAnexo.setText("");
    Anexo = null;

}//GEN-LAST:event_BotaoExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContatoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContatoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContatoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContatoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ContatoTela().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Assunto;
    private javax.swing.JButton BotaoAnexo;
    private javax.swing.JButton BotaoEnviar;
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JTextField Destinatario;
    private javax.swing.JTextField EnderecoAnexo;
    private javax.swing.JTextArea Mensagem;
    private javax.swing.JTextField Porta;
    private javax.swing.JTextField ServidorSMTP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private JTextField NomeRemetente;
    private JLabel label;
    // End of variables declaration//GEN-END:variables

    public void EmailAnexo() {
        try {

            //usuario e senha do seu gmail
            final String usuario = "ti1@masottiinvestimentos.com.br";
            final String senha = "Masotti12365";

            //config. do gmail
            Properties mailProps = new Properties();
            mailProps.put("mail.transport.protocol", "smtp");
            mailProps.put("mail.smtp.starttls.enable", "true");
            mailProps.put("mail.smtp.host", ServidorSMTP.getText());
            mailProps.put("mail.smtp.auth", "true");
            mailProps.put("mail.smtp.user", usuario);
            mailProps.put("mail.debug", "true");
            mailProps.put("mail.smtp.port", Porta.getText());
            mailProps.put("mail.smtp.socketFactory.port", Porta.getText());
            mailProps.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
            mailProps.put("mail.smtp.socketFactory.fallback", "false");

            //eh necessario autenticar
            Session mailSession = Session.getInstance(mailProps, new Authenticator() {

                public PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(usuario, senha);
                }
            });
            mailSession.setDebug(false);

            //config. da mensagem
            Message mailMessage = new MimeMessage(mailSession);

            //remetente
            mailMessage.setFrom(new InternetAddress(usuario, NomeRemetente.getText()));

            //destinatario
            mailMessage.setRecipients(Message.RecipientType.TO, InternetAddress.parse(Destinatario.getText()));

            //mensagem que vai no corpo do email
            MimeBodyPart mbpMensagem = new MimeBodyPart();
            mbpMensagem.setText(Mensagem.getText());

//			partes do email
            Multipart mp = new MimeMultipart();
            mp.addBodyPart(mbpMensagem);
            
            String Endereco_Anexo = "";
            if (Anexo != null) { // se tiver alguma coisa anexada ela inicializar o comando abaixo
                for (File element : Anexo) {

                    Endereco_Anexo = element.getPath();
                    String imagem = Endereco_Anexo;
                    File Arquivo = new File(imagem);
                    //setando o anexo
                    MimeBodyPart mbpAnexo = new MimeBodyPart();
                    mbpAnexo.setDataHandler(new DataHandler(new FileDataSource(Arquivo)));
                    mbpAnexo.setFileName(Arquivo.getName());
                    mp.addBodyPart(mbpAnexo);
                }
            }

            //assunto do email
            mailMessage.setSubject(Assunto.getText());

            //seleciona o conteudo 
            mailMessage.setContent(mp);

            //envia o email
            Transport.send(mailMessage);
           
            JOptionPane.showMessageDialog(null, "Email Enviado com Sucesso");
            Mensagem.setText("");
            Assunto.setText("");
       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Houve um erro no Envio !\n"+e);
        }
    }


// public void EmailSimples() throws UnsupportedEncodingException {
//
//        Properties props = new Properties();
//        /** Par√¢metros de conex√£o com servidor Gmail */
//        props.put("mail.smtp.host", ServidorSMTP.getText());
//        props.put("mail.smtp.socketFactory.port", Porta.getText());
//        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
//        props.put("mail.smtp.auth", "true");
//        props.put("mail.smtp.port", Porta.getText());
//
//        Session session = Session.getDefaultInstance(props,
//                new javax.mail.Authenticator() {
//
//                    protected PasswordAuthentication getPasswordAuthentication() {
//                        return new PasswordAuthentication(Remetente.getText(), Senha.getText());
//                    }
//                });
//
//        /** Ativa Debug para sess√£o */
//        session.setDebug(true);
//
//        try {
//
//            Message message = new MimeMessage(session);
//            message.setFrom(new InternetAddress(Remetente.getText(), NomeRemetente.getText())); //Remetente
//
//            Address[] toUser = InternetAddress //Destinat√°rio(s)
//                    .parse(Destinatario.getText());
//
//            message.setRecipients(Message.RecipientType.TO, toUser);
//            message.setSubject(Assunto.getText());//Assunto
//            message.setText(Mensagem.getText());
//            /**M√©todo para enviar a mensagem criada*/
//            Transport.send(message);
//
//            System.out.println("Feito!!!");
//            JOptionPane.showMessageDialog(null, "Email Enviado com Sucesso");
//
//        } catch (MessagingException e) {
//            JOptionPane.showMessageDialog(null, "Houve um erro no Envio !");
//            throw new RuntimeException(e);
//
//        }
//    }


}