package view;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

import javax.swing.*;

import com.myscrum.controller.Controle;
import com.myscrum.controller.Controlev;

public class MenuBar extends JFrame {
	
	/**
	 * Desenvolvido por Abner Matias e Pedro Henrique
	 * 
	 */
	private static final long serialVersionUID = 1L;
	Controlev control = new Controlev();
	
	public static void main(String[] args) {
	}	
  
public MenuBar() {
	  
	  //set iniciais
	  super("Configurações");//titulo do frame	
	  setSize(435, 400);//define o tamanho do frame
	  setResizable(false);
        
      //Setando Icone do Frame
      java.net.URL url = this.getClass().getResource("/com/myscrum/assets/setIcon1.png");  
      Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);  
      this.setIconImage(iconeTitulo);
      
      //Criação do objeto de menu
  	  JTabbedPane tabbedPane = new JTabbedPane();
      
      JPanel card1 = new CcCustoTela();
      card1.setLayout(null);
      
      JPanel card2 = new DptoTela();
      card2.setLayout(null);
      
      JPanel card3 = new TamanhoTela();
      card3.setLayout(null);
      
      JPanel card4 = new FeriadoTela();
      card4.setLayout(null);

      JPanel card5 = new ProcessosTela();
      card5.setLayout(null);
      
      JPanel card6 = new EtapaTela();
      card6.setLayout(null);
      
      JPanel card7 = new SubEtapaTela();
      card7.setLayout(null);
      
      //Criando botões no menu e setando seu paineis referentes
  
      tabbedPane.addTab("Centros de Custo", card1);
      tabbedPane.addTab("Departamentos", card2);
      tabbedPane.addTab("Tamanho", card3);
      tabbedPane.addTab("Feriados", card4);
      tabbedPane.addTab("Processos", card5);
      tabbedPane.addTab("Etapa", card6);
      tabbedPane.addTab("SubEtapa", card7);
   
      add(tabbedPane, BorderLayout.CENTER);
      
      //propriedades do frame 
      setLocationRelativeTo(null);//localidade do frame referente a tela(centraliza o frame)
      setVisible(true);//habilita visualização do frame
      setBackground(Color.WHITE); 
      
      	//metodos da janela
      addWindowListener(new WindowListener() {
		public void windowOpened(WindowEvent e) {
		}
		public void windowIconified(WindowEvent e) {
		}
		public void windowDeiconified(WindowEvent e) {
		}
		public void windowDeactivated(WindowEvent e) {
		}
		public void windowClosing(WindowEvent e) {
			Controle.setMenu(false);
		}
		public void windowClosed(WindowEvent e) {
		}
		public void windowActivated(WindowEvent e) {
		}
	});
    } 
}

