package view;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;

import javax.swing.*;

import com.myscrum.banco.BD;
import com.myscrum.model.Redimensionar;
import com.myscrum.model.SubEtapa;
import com.myscrum.model.SubEtapaDAO;
import com.myscrum.model.CcCusto;
import com.myscrum.model.CcCustoDAO;

public class SubEtapaTela extends JPanel {

	/**
	 * Desenvolvido por Abner Matias e Pedro Henrique
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private JComboBox<String> subEtapaCombo;
	private JTextField subEtapaText;
	private JButton salvarButton;
	private JButton atualizarButton;
	private JLabel subEtapaLabel;
	private JLabel cadastradoLabel;
	Redimensionar rsize = new Redimensionar();
	JPanel panel = new JPanel();

	SubEtapaDAO metodos = new SubEtapaDAO();
	BD bd = new BD();
	String sql;

	public SubEtapaTela() {
		// construct preComponents
		String[] subEtapaComboItems = { "Selecione subetapa" };

		// construct components
		subEtapaCombo = new JComboBox<String>(subEtapaComboItems);
		subEtapaText = new JTextField(5);
		salvarButton = new JButton("Salvar");
		atualizarButton = new JButton("Atualizar");
		atualizarButton.setEnabled(false);
		subEtapaLabel = new JLabel("Sub etapa:");
		cadastradoLabel = new JLabel("Já cadastrado:");

		setBackground(Color.WHITE);

		// adjust size and set layout
		setPreferredSize(new Dimension(400, 400));

		// add components
		add(subEtapaCombo);
		add(subEtapaText);
		add(salvarButton);
		add(atualizarButton);
		add(subEtapaLabel);
		add(cadastradoLabel);

		// set component bounds (only needed by Absolute Positioning)
		subEtapaCombo.setBounds(110, 140, 210, 25);
		subEtapaCombo.setBackground(new Color(41, 106, 158));
		subEtapaCombo.setForeground(Color.WHITE);
		subEtapaText.setBounds(110, 75, 210, 30);
		subEtapaText.setBackground(new Color(41, 106, 158));
		subEtapaText.setForeground(Color.WHITE);
		salvarButton.setBounds(250, 265, 120, 35);
		salvarButton.setBackground(new Color(163, 184, 204));
		atualizarButton.setBounds(50, 265, 120, 35);
		atualizarButton.setBackground(new Color(163, 184, 204));
		subEtapaLabel.setBounds(110, 50, 95, 25);
		cadastradoLabel.setBounds(110, 115, 95, 25);

		String etapa = null;
		// Preenchendo a combo box
		try {
			sql = "SELECT * FROM sub_etapas";
			bd.getConnection();
			bd.st = bd.con.prepareStatement(sql);
			bd.rs = bd.st.executeQuery();
			while (bd.rs.next()) {
				etapa = bd.rs.getString("sub_etapa");
				subEtapaCombo.addItem(etapa);
			}
			bd.close();
		} catch (SQLException erro) {
			JOptionPane.showMessageDialog(null, erro.toString());
		}
		// FIM

		subEtapaCombo.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (subEtapaCombo.getSelectedIndex() == 0) {
					salvarButton();
					subEtapaText.setText("");
				} else {
					atualizarButton();
					subEtapaText.setText(subEtapaCombo.getSelectedItem().toString());
				}
			}
		});

		salvarButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				int escolha;
				if (subEtapaText.getText().equals("")) {
					JOptionPane.showMessageDialog(null, "Preencha o campos corretamente", "Campo Vazio", 0);
				} else if (subEtapaText.getText().equals(subEtapaCombo.getSelectedItem().toString())) {
					JOptionPane.showMessageDialog(null, "Altere o nome da etapa para atualizar", "Mensagem", 0);
				} else {
					escolha = JOptionPane.showConfirmDialog(null,
							"Deseja realmente cadastrar " + subEtapaText.getText() + " como etapa ?",
							"Selecione uma opção", JOptionPane.YES_NO_OPTION);
					if (escolha == JOptionPane.YES_OPTION) {
						SubEtapa subetapa = new SubEtapa(subEtapaText.getText());
						
						metodos.cadastrar(subetapa);
						carregarComboBox();
						subEtapaText.setText("");
					}
				}
			}
		});

		atualizarButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				int escolha;
				if (subEtapaText.getText().equals("")) {
					JOptionPane.showMessageDialog(null, "Preencha o campos corretamente", "Campo Vazio", 0);
				} else if (subEtapaText.getText().equals(subEtapaCombo.getSelectedItem().toString())) {
					JOptionPane.showMessageDialog(null, "Altera o nome da etapa para atualizar", "Mensagem", 0);
				} else {
					escolha = JOptionPane
							.showConfirmDialog(null,
									"Deseja realmente alterar " + subEtapaCombo.getSelectedItem().toString() + " para "
											+ subEtapaText.getText() + " ?",
									"Selecione uma opção", JOptionPane.YES_NO_OPTION);
					if (escolha == JOptionPane.YES_OPTION) {
						SubEtapa subetapa = new SubEtapa(subEtapaCombo.getSelectedItem().toString(), subEtapaText.getText());
						
						metodos.atualizar(subetapa);
						carregarComboBox();
						subEtapaText.setText("");
					}
				}
			}
		});
	}

	public void atualizarButton() {
		atualizarButton.setEnabled(true);
		salvarButton.setEnabled(false);
	}

	public void salvarButton() {
		salvarButton.setEnabled(true);
		atualizarButton.setEnabled(false);
	}

	public void carregarComboBox() {
		String etapa = null;
		String a;
		int b = 1;
		// Esvaziando a combobox
		while (b < subEtapaCombo.getItemCount()) {
			a = subEtapaCombo.getItemAt(b).toString();
			subEtapaCombo.removeItem(a);
		}

		// Preenchendo a combo box
		try {
			sql = "SELECT * FROM sub_etapas";
			bd.getConnection();
			bd.st = bd.con.prepareStatement(sql);
			bd.rs = bd.st.executeQuery();
			while (bd.rs.next()) {
				etapa = bd.rs.getString("sub_etapa");
				subEtapaCombo.addItem(etapa);
			}
			bd.close();
		} catch (SQLException erro) {
			JOptionPane.showMessageDialog(null, erro.toString());
		}
	}
}
